echo "

[01].SUNTIK TIKTOK DEV LORDHOZOO                   
[02].DEFACE JSO
[03].SUNTIK SUBCERIBE YOUTUBE  DEV LORDHOZOO     
[04].DDOS GAME UDP  DEV LORDHOZOO     
[05].TXT BANNED FOR UNBANNED WHATS APP  DEV LORDHOZOO     
[06].SPAM OTP WA FOR SPAM PAIR CODE  DEV LORDHOZOO     
[07].SPAM BOT TOKEN TELEGRAM IMAGE URL  DEV LORDHOZOO     
[08].BIKIN APLIKASI MENGGUNAKAN TERMUX RANSOMWWER APK INI TERKUNCI LAYAR HP ANDA TEMBUSAN SEKITAR ANDA ISI SENDIRI
[09].VIRUS TERMUX FITURE APA SIH KALO DI JALANKAN DI TERMUX KARENA VIRUS NAMA PENGHAPUS GALERY POTO  
[10].SPAM SMS ULIMITID COCOK UNTUK LU JAHIL TEMEN MAIN GAME DLL
[11].INSTALL KALI LINUX APA TUJUAN LU INSTALL KALI LINUX DI TERMUX MAU JJ DEPAN DESKTOP APA LU JAGO HACKING TERMUX TAPI RESIKO TANGGUNG JAWAB LU GAK PAKE VPN KOCAK
[12].VPN TERMUX ALAT INI MENGAMATKAN DEVICE HP ANDA KARENA KALO ANDA BUKA WWEB KLICK LINK GAK JELAS IP LU GAK TERDETEKSI KARENA VPN TERMUX INI KUAT TERHADAP VPN NYA
[13].BANNED TIKTOK MASUKAN USER LINK APA TUJUAN BANNED TIKTOK KARENA ANDA PENGEN BALES DEMDAM DI KOMENTAR DLL DI KATAIN DAN DI HINA DAN ANDA ADA PIKIR ORANG POST TIKTOK VIDIO LINK PSISING KARENA ANDA PUNYA IDE PINTER NYA KAMU
[14].BANNED GAME FREE FIRE TAPI KENAPA ANDA BANNED AKUN GAME APA TUJUAN NYA KARENA TUJUAN NYA SAYA KESAL DI BULY GAME PAMER SKIN SOK SULTAN HINA DAN AKUN KAMU BOT METODE INI HARD BANNED 
[15].DONASI LORDHOZOO  TUJUAN DONASI SAYA KARENA SAYA PENGEN PUBLIKASI TOOLS DI JUAL KARENA INI METODE PREMIUM DI BUAT TOOOLS TAHUN 2025
[16].TIKTOK LORDHOZOO BANTU FOLLOWERS GES
[17].YT LORDHOZOO BANTU SUBCERIBE LIKE KOMEN SHER GES SUPPORT GW -_-
[18].UPDATE TOOLS KANDURA EXECUTORLORDHOZOO
[19].PENGHAPUSAN TOOLS AGAR GAK PENUH MEMORI TERMUX SAAT INSTALL NYA GESS KALO MAIN TERMUX HARUS RAM 3 4 
[20].ABAOUT LORDHOZOO

"

read -p "ROOT@LORDHOZOO :"
